---------
**Very useful commands for Org Mode:**
- `C-c C-o` navigates to link
- `C-c C-x C-v` displays inline images
- `C-c C-x C-l` previews $LaTeX$
- `C-c C-l` inserts a link
- `Space o A` opens agenda mode
- `C-c C-s` schedules a schedule/schedules a deadline 
- `C-c C-x C-s` archives the subtree
---------
    
* All about OGP
** Feedback on my interview
initiative => strong, working on all sorts of stuff, blog it out, outline my thoughts, interview prep
ability => resume deep dive with nikhil and chinying not that impressive (question mark), but Hong thought the bayesian SMS was deep enough (dispelled doubts about technical depth)

CHin ying noted familiar with complexity, made it about halfway trhough the question, i do plan and talk about high level approaches and considerations, but coding ended up a bit chaotic. Need to work on explaining the code (but great I explained it before i started writing). He said I had more experience i would be able to handle the edge cases

Nikhil's question: went a lot more smoothly, got stuck but managed to get unstuck which is good, he said I could code fast, i knew what i could do to refactor, i knew algo complexity, decent,

More generally on communication: I'm a good communicator especially on the technical interview, Everyone noted I was able to speak clearly and well, BUT i do tend to talk extensively/waffle at the theoretical or high level, and it takes some time to get to the actual nuts and bolts <— this was hongyi's feedback. Overall strong communicator

My personal suggestion (from Russell) —> great at documenting and preparing, but don't be compelled to say eveyrthing you prepare.

especially for someone who comes from a nontraditional background, I have a good technical depth and side projects

"work is very good, nontrivial side-projects, especially for someone non traditional , but technical depth not as good as the best engineer candidates" — verbatim quote from hongyi

strong initiative —> good fit for team

strong communicator (only minor tuning needed)

strong POTENTIAL for technical depth
** Leveling Philosophy:
[[./docs/Levelling_Performance_Promotions.pdf]]
[[./docs/Software_Engineer_Career_Schema.pdf]]
** Pay:
*Software Developer*
SD1 77
SD2 95

*Associate Software Engineer*
ASE1 116 <— the CS grads with a traditional background come in here
ASE2 127
ASE3 139

*Software Engineer*
SE1 <— 151,005
SE2
SE3: because they're better, ppl come to them for mentorship

*Senior Software Engineer*
SSE1 <— 210,500: resting level for engineers
SSE2
SSE3

Deliberately mapping nicely to Google's own system:
L3 is Associate
L4 is Core
L5 is Senior
L6 is Staff
** Next steps:
Hey Zheng Hong - had a quick chat with the Govtech HR team. They clarified next steps:

The next steps from here are:

Zheng Hong will need to enquire from IMDA the Liquidated Damage (LD) amount – for Govtech HR to present to Govtech CE as the amount we need to pay for the transfer.

Zheng Hong will then need to meet with representatives from the Govtech Senior Leadership Team for an interview, before Govtech can confirm that they will be proceeding with the bond transfer

When Zheng Hong is accepted by SLM, Govtech HR will follow through with IMDA on the transfer payment.

I've clarified with them for their advice on how you should approach IMDA HR. They suggested that until you have the interview with the Govtech senior leadership team, you could position this as a general query to understand your LD. Whilst its accurate to say that you have cleared Govtech interviews and OGP would be happy to take you in as a software engineer, it would be premature to also inform IMDA that Govtech has agreed to takeover your bond, as this requires govtech senior leadership approval (hence the interview).
* Salaries of different roles
Global Markets Analyst, HSBC, 9.2k (110k pa) + 3 month bonus
Analyst, IB Credit Suisse, 10k monthly (120k pa) + bonus
Consultant, Bain, 6.5k monthly (75k pa) + 10k bonus
SWE, Jump Trading, 135k base (never increases), discretionary bonus with no cap (i.e. goes up infinitely)

DX9, MINDEF, 3850 + 300 allowance (total 4150)
Stripe: 100k base, 160k USD stocks vesting over 4 years, sign on bonus 30k SGD, 10-15% yearly bonus
Jane Street HK: 450k SGD lol disgusting

van chia: 140k GBP after TC
* CKY's thoughts on how to Make ADM Great Again
lieu, [09.10.20 12:07]
now that youve come to the end ish of your NTU ADM journey
if you were the NTU ADM tsar
how would you design the degree

:CKY:
game design should be a separate dedicated pathway
theres no way u can shoehorn it into an art school style system
u need an entire school dedicated to it, digipen style
u have pathways for art, programming, level design, and business
everyone is required to take the intro level course of each pathway
im not familiar with the school structure of digipen
anyway the key innovation would be that very early on, you divide students into groups of 4
u pair up one member from each pathway
and then u prototype shit like crazy, every semester build a game together
thats what i would propose if the dean asked me
no comment on the fine arts side, fine arts is all bs anyway so you can literally teach nothing and students can still become artists
maybe u are overseen by a mentor, you have the chance to change team every semester
the key thing is that u build team competencies from the get go
and you allow teams to stick together if they want
this encourages effective close knit cells to form
thats how u get masterpieces
also right the standards for game design course need to be set way the fuck higher
because im in all half fuck courses
and i know that most of my course mates have no future except making secondary assets for gacha games
people supposedly in final year at uni but they make some garbage newgrounds 3 star quality flash game
how to compete with digipen
:END:

*Lieu:*
what's the quality of people in digipen

:CKY:
also not amazing but at least digipen can deliver something that looks like sweatshop quality
as opposed to "babby's first unity game" quality
if u go game design pathway the expectation is that it gives u a minimum standard of competency to be a good fit in the industry
rn this is absolutely not the case in my opinion
a lot of people will have their dreams crushed
:END:

*Lieu:*
does game design include programming or not

*CKY:*
yes but the programming is very basic

*Lieu:*
should it need to include programming

:CKY:
and the math level of this cohort is abysmal
yes absolutely
at least the basics
:END:

*Lieu:*
you can do writing/world design right
be like a D&D writer
or something
you get me
or an artist

:CKY:
how many randomly selected art students do you think are actually capable of writing coherent prose
these are not oxford students
these are literal hipsters who think instagram is cool
do u expect them to understand economics, history, politics, and all the other things that go into worldbuilding
so realistically right, these people will become game artists 99% of the time
except, animation is a way better pathway for game artists
game design tries to be this half fuck grab bag and ends up teaching too low a standard of programming AND too low a standard of art
no matter how you look at it though, ADM in its current state is a waste of time and resources
at least for my courses
:END:

* Entrepreneurship
** [[https://commoncog.com/blog/just-f-cking-ship/][Just Fucking Ship]]: book by Amy Hoy
*** Set a Deadline and Mean It
*** Work Backwards
* Board Game Engine
** Gameboard-1: [[https://www.youtube.com/watch?v=BRnjbP0trug&app=desktop][very cool hardware project]]
* [[https://news.ycombinator.com/item?id=24934722][What Would Mechanical Programming Look Like?]]
